=== usnistgov/soup-xlm/cp-adl/causalchain.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (http://www.altova.com) by Martin Burns (National Institute of Standards and Technology) -->
<!--W3C XML Schema generated by XMLSpy v2020 rel. 2 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Attack" type="Attack"/>
	<xs:complexType name="Attack">
		<xs:sequence>
			<xs:element name="CausalChain" type="CausalChain" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Element" type="Element" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="CausalChain" type="CausalChain"/>
	<xs:complexType name="CausalChain">
		<xs:sequence>
			<xs:element name="Attack" type="Attack" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Element" type="Element"/>
	<xs:complexType name="Element">
		<xs:sequence>
			<xs:element name="Actor" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ElementName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="MethodName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Realm" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Si" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Sn" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Effects" type="Effects" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Element" type="Element" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="AffectedElement" type="AffectedElement"/>
	<xs:complexType name="AffectedElement">
		<xs:complexContent>
			<xs:extension base="ElementPart">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Effects" type="Effects"/>
	<xs:complexType name="Effects">
		<xs:sequence>
			<xs:element name="Action" type="Action" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="Cause" type="Cause" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="StateTransion" type="StateTransion" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Impact" type="Impact"/>
	<xs:complexType name="Impact">
		<xs:complexContent>
			<xs:extension base="Change">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Tuple_AffectedElement_Influenc" type="Tuple_AffectedElement_Influenc"/>
	<xs:complexType name="Tuple_AffectedElement_Influenc">
		<xs:sequence>
			<xs:element name="AffectedElement" type="AffectedElement" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Effects" type="Effects" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Impact" type="Impact" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="StateTransion" type="StateTransion"/>
	<xs:complexType name="StateTransion">
		<xs:complexContent>
			<xs:extension base="ElementPart">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Cause" type="Cause"/>
	<xs:complexType name="Cause">
		<xs:complexContent>
			<xs:extension base="ElementPart">
				<xs:sequence>
					<xs:element name="Tuple_InfluencedElement_Influence" type="Tuple_InfluencedElement_Influence" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Influence" type="Influence"/>
	<xs:complexType name="Influence">
		<xs:complexContent>
			<xs:extension base="Change">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="InfluencedElement" type="InfluencedElement"/>
	<xs:complexType name="InfluencedElement">
		<xs:complexContent>
			<xs:extension base="ElementPart">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Tuple_InfluencedElement_Influence" type="Tuple_InfluencedElement_Influence"/>
	<xs:complexType name="Tuple_InfluencedElement_Influence">
		<xs:sequence>
			<xs:element name="Influence" type="Influence" minOccurs="1" maxOccurs="1"/>
			<xs:element name="InfluencedElement" type="InfluencedElement" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Action" type="Action"/>
	<xs:complexType name="Action">
		<xs:complexContent>
			<xs:extension base="ElementPart">
				<xs:sequence>
					<xs:element name="ActionOption" type="ActionOption" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ActionOption" type="ActionOption"/>
	<xs:complexType name="ActionOption">
		<xs:sequence>
			<xs:element name="Tuple_Method_Preconditions" type="Tuple_Method_Preconditions" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Method" type="Method"/>
	<xs:complexType name="Method">
		<xs:sequence>
			<xs:element name="Category" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Preconditions" type="Preconditions" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Precondition" type="Precondition"/>
	<xs:complexType name="Precondition">
		<xs:sequence>
			<xs:element name="Category" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Desciption" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Preconditions" type="Preconditions"/>
	<xs:complexType name="Preconditions">
		<xs:sequence>
			<xs:element name="Precondition" type="Precondition" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Tuple_Method_Preconditions" type="Tuple_Method_Preconditions"/>
	<xs:complexType name="Tuple_Method_Preconditions">
		<xs:sequence>
			<xs:element name="Method" type="Method" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="Preconditions" type="Preconditions" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Change" type="Change"/>
	<xs:complexType name="Change">
		<xs:sequence>
			<xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Type" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ElementPart" type="ElementPart"/>
	<xs:complexType name="ElementPart">
		<xs:sequence>
			<xs:element name="Category" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== usnistgov/soup-xlm/cp-adl/cp-adl.xml
<?xml version="1.0" encoding="UTF-8"?>
<CausalChain xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="causalchain.xsd">
	<Attack>
		<Element>
			<ElementName>Elements(2)</ElementName>
			<MethodName>Methods(2)</MethodName>
			<Realm>T</Realm>
			<Si>S2i</Si>
			<Sn>S2n</Sn>
			<Effects>
				<Action>
					<Category>1</Category>
					<Name/>
				</Action>
				<Cause>
					<Category>1</Category>
					<Name/>
				</Cause>
				<StateTransion>
					<Category>1</Category>
					<Name>S1</Name>
				</StateTransion>
			</Effects>
		</Element>
	</Attack>
</CausalChain>

=== usnistgov/soup-xlm/cp-adl/Nanosatellite Scenario Description.xml
<?xml version="1.0" encoding="UTF-8"?>
<CausalChain xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="causalchain.xsd">
	<Attack>
		<Element>
			<Actor>PayloadComputer</Actor>
			<ElementName>Elements(0)</ElementName>
			<MethodName/>
			<Realm>L</Realm>
			<Si/>
			<Sn/>
			<Element>
				<Actor>PayloadComputer</Actor>
				<ElementName>Elements(1)</ElementName>
				<MethodName/>
				<Realm>L</Realm>
				<Si/>
				<Sn/>
			</Element>
		</Element>
		<Element>
			<Actor>Command/DataComp</Actor>
			<ElementName>Elements(0)</ElementName>
			<MethodName/>
			<Realm>L</Realm>
			<Si/>
			<Sn/>
			<Element>
				<Actor>Command/DataComp</Actor>
				<ElementName>Elements(1)</ElementName>
				<MethodName/>
				<Realm>L</Realm>
				<Si/>
				<Sn/>
			</Element>
		</Element>
		<!-- main channel -->
		<Element>
			<Actor>MaliciousActor</Actor>
			<ElementName>Elements(0)</ElementName>
			<MethodName>Methods(0)</MethodName>
			<Realm>H</Realm>
			<Si>S1i</Si>
			<Sn>S1n</Sn>
			<Effects>
				<Action>
					<Category>1</Category>
					<Name>A1</Name>
				</Action>
				<Cause>
					<Category>1</Category>
					<Name>C1</Name>
				</Cause>
				<StateTransion>
					<Category>1</Category>
					<Name>S1</Name>
				</StateTransion>
			</Effects>
			<Element>
				<Actor>MaliciousRSO</Actor>
				<ElementName>Elements(2)</ElementName>
				<MethodName>Methods(2)</MethodName>
				<Realm>P</Realm>
				<Si>S2i</Si>
				<Sn>S2n</Sn>
				<Element>
					<Actor>Camera</Actor>
					<ElementName>Element(3)</ElementName>
					<MethodName/>
					<Realm>T</Realm>
					<Si/>
					<Sn/>
					<Element>
						<Actor>PayloadComputer</Actor>
						<ElementName>Element(4)</ElementName>
						<MethodName/>
						<Realm>L</Realm>
						<Si/>
						<Sn/>
						<Element>
							<Actor>Command/DataComp</Actor>
							<ElementName>Element(5)</ElementName>
							<MethodName/>
							<Realm>L</Realm>
							<Si/>
							<Sn/>
							<Element>
								<Actor>SecureRadio</Actor>
								<ElementName>Element(6)</ElementName>
								<MethodName/>
								<Realm>T</Realm>
								<Si/>
								<Sn/>
								<Element>
									<Actor>MaliciousActor</Actor>
									<ElementName>Element(7)</ElementName>
									<MethodName/>
									<Realm>H</Realm>
									<Si/>
									<Sn/>
									<Element>
										<Actor>SecureRadio</Actor>
										<ElementName>Element(8)</ElementName>
										<MethodName/>
										<Realm>T</Realm>
										<Si/>
										<Sn/>
										<Element>
											<Actor>Command/DataComp</Actor>
											<ElementName>Element(9)</ElementName>
											<MethodName/>
											<Realm>L</Realm>
											<Si/>
											<Sn/>
											<Element>
												<Actor>PropValveActuator</Actor>
												<ElementName>Element(10)</ElementName>
												<MethodName/>
												<Realm>T</Realm>
												<Si/>
												<Sn/>
												<Element>
													<Actor>PropulsionSystem</Actor>
													<ElementName>Element(11)</ElementName>
													<MethodName/>
													<Realm>P</Realm>
													<Si/>
													<Sn/>
													<Element>
														<Actor>NanosatMass</Actor>
														<ElementName>Element(12)</ElementName>
														<MethodName/>
														<Realm>P</Realm>
														<Si/>
														<Sn/>
														<Element>
															<Actor>MaliciosRSO</Actor>
															<ElementName>Element(13)</ElementName>
															<MethodName/>
															<Realm>P</Realm>
															<Si/>
															<Sn/>
															<Element>
																<Actor>HVA</Actor>
																<ElementName>Element(14)</ElementName>
																<MethodName/>
																<Realm>P</Realm>
																<Si/>
																<Sn/>
															</Element>
														</Element>
													</Element>
												</Element>
											</Element>
										</Element>
									</Element>
								</Element>
								<Element>
									<Actor>GroundTeam</Actor>
									<ElementName/>
									<MethodName/>
									<Realm/>
									<Si/>
									<Sn/>
								</Element>
							</Element>
						</Element>
					</Element>
				</Element>
			</Element>
		</Element>
	</Attack>
</CausalChain>
